server:
  port: 2000

client:
  id: YOUR_CLIENT_ID
  secret: YOUR_CLIENT_SECRET

access:
  token:
    url: https://demo.kyriba.com/gateway/oauth/token

base:
  url: https://demo.kyriba.com/gateway/api

list:
  apis:
    - /v1/accounts
    - /v1/third-parties
    - /v1/users
    - /v1/companies
    - /v1/banks
    - /v1/bank-branches
    - /v1/supplier-users
    - /v1/bank-balances/accounts
    - /v1/cash-balances/accounts
    - /v1/data-permissions
    - /v1/data-permission-profiles
    - /v1/account-groups

api:
  fields:
    /v1/accounts:
      - code
      - uuid
      - calendar.code
      - currency.code
      - company.code
      - branch.code
      - bankAccountID.banStructure
      - bankAccountID.value
      - address.country.code
      - timeZone

    /v1/third-parties:
      - code
      - name
      - address.country.code

    /v1/users:
      - acceleratorForMillions
      - acceleratorForThousands
      - accessProfile.code
      - code
      - decimalSeparator
      - email
      - firstName
      - lastName
      - preferredContactChannel
      - thousandSeparator
      - timeZone
      - title
      - interfaceCode
      - fax
      - mobilePhone
      - officePhone

    /v1/companies:
      - address.country.code
      - code
      - currencies.currency.code
      - currencies.glCurrency.code
      - interfaceCode
      - shortCode

    /v1/banks:
      - address.country.code
      - code
      - interfaceCode

    /v1/bank-branches:
      - code
      - interfaceCode
      - bank.code
      - address.country.code
      - calendar.code
      - timeZone

    /v1/supplier-users:
      - code
      - thirdParty.code
      - companyOwnership.code
      - accessProfile.code
      - firstName
      - lastName
      - preferredContactChannel
      - email
      - timeZone
      - interfaceCode
      - fax
      - mobilePhone
      - officePhone
      - uuid

    /v1/bank-balances/accounts:
      - account.code
      - bankBalance.amount

    /v1/cash-balances/accounts:
      - account.code
      - cashBalance.amount

    /v1/data-permissions:
      - code
      - uuid

    /v1/data-permission-profiles:
      - code
      - dataType
      - type
      - uuid

    /v1/account-groups:
      - accounts[].code
      - code
      - poolingAccount.code
      - uuid

#List of all possible methods: [GET_ALL, GET_BY_CODE, GET_BY_UUID, POST, PUT_BY_CODE, PUT_BY_UUID, DELETE_BY_CODE, DELETE_BY_UUID]
  methods:
    /v1/accounts:
      - GET_ALL
      - GET_BY_CODE
      - GET_BY_UUID
      - POST
      - PUT_BY_CODE
      - PUT_BY_UUID
      - DELETE_BY_CODE
      - DELETE_BY_UUID

    /v1/third-parties:
      - GET_ALL
      - GET_BY_CODE
      - GET_BY_UUID
      - POST
      - PUT_BY_CODE
      - PUT_BY_UUID
      - DELETE_BY_CODE
      - DELETE_BY_UUID

    /v1/users:
      - GET_ALL
      - GET_BY_UUID
      - POST
      - PUT_BY_UUID
      - DELETE_BY_UUID

    /v1/companies:
      - GET_ALL
      - GET_BY_UUID
      - POST
      - PUT_BY_UUID
      - DELETE_BY_CODE
      - DELETE_BY_UUID

    /v1/banks:
      - GET_ALL
      - GET_BY_CODE
      - GET_BY_UUID
      - POST
      - PUT_BY_CODE
      - PUT_BY_UUID
      - DELETE_BY_CODE
      - DELETE_BY_UUID

    /v1/bank-branches:
      - GET_ALL
      - GET_BY_CODE
      - GET_BY_UUID
      - POST
      - PUT_BY_CODE
      - PUT_BY_UUID
      - DELETE_BY_CODE
      - DELETE_BY_UUID

    /v1/supplier-users:
      - GET_ALL
      - GET_BY_UUID
      - POST
      - PUT_BY_UUID
      - DELETE_BY_UUID

    /v1/bank-balances/accounts:
      - GET_BY_CODE
      - GET_BY_UUID

    /v1/cash-balances/accounts:
      - GET_BY_CODE
      - GET_BY_UUID

    /v1/data-permissions:
      - GET_ALL
      - GET_BY_CODE
      - GET_BY_UUID

    /v1/data-permission-profiles:
      - GET_ALL
      - GET_BY_CODE
      - GET_BY_UUID

    /v1/account-groups:
      - GET_ALL
      - GET_BY_UUID
      - POST
      - PUT_BY_UUID
      - DELETE_BY_UUID

#For boolean fields values can be only 'true' or 'false'
enums:
  available:
    values:
      /v1/accounts:
        bankAccountID.banStructure:
          - BBAN_STRUCTURE
          - IBAN_STRUCTURE
          - LBAN_0_STRUCTURE
          - LBAN_1_STRUCTURE
          - LBAN_2_STRUCTURE
          - LBAN_3_STRUCTURE
          - LBAN_4_STRUCTURE
          - LBAN_5_STRUCTURE
          - LBAN_6_STRUCTURE
          - LBAN_7_STRUCTURE
          - LBAN_8_STRUCTURE
          - LBAN_9_STRUCTURE

      /v1/users:
        preferredContactChannel:
          - OFFICE_PHONE
          - MOBILE_PHONE
          - EMAIL
          - BY_FAX

        title:
          - NONE
          - DR
          - MISS
          - MR
          - MRS
          - MS

      /v1/supplier-users:
        preferredContactChannel:
          - OFFICE_PHONE
          - MOBILE_PHONE
          - EMAIL
          - BY_FAX

      /v1/data-permission-profiles:
        dataType:
          - COMPANY
          - USER_GROUP

        type:
          - GENERAL
          - BY_FUNCTION